name: Cross Compile buaalogin for OpenWRT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Nim Compiler
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.0' # default is 'stable'

      - name: Setup OpenWRT Toolchain
        run: |
          mkdir -p $HOME/openwrt
          cd $HOME/openwrt
          wget -q -c https://downloads.openwrt.org/releases/22.03.5/targets/ramips/mt7621/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          tar xvf openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64.tar.xz
          export PATH=$HOME/openwrt/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin:$PATH

      - name: Configure Nim for Cross Compilation
        run: |
          echo "mipsel.linux.gcc.path = \"$HOME/openwrt/openwrt-toolchain-22.03.5-ramips-mt7621_gcc-11.2.0_musl.Linux-x86_64/toolchain-mipsel_24kc_gcc-11.2.0_musl/bin\"" >> src/nim.cfg
          echo "mipsel.linux.gcc.exe = \"mipsel-openwrt-linux-gcc\"" >> src/nim.cfg
          echo "mipsel.linux.gcc.linkerexe = \"mipsel-openwrt-linux-gcc\"" >> src/nim.cfg

      - name: Compile buaalogin
        run: nimble build -y

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v3   
        with:
          name: buaalogin-mipsle
          path: |
              ./buaalogin
